[versions]
androidGradlePlugin = "8.4.0"
androidxActivity = "1.9.0"
androidxComposeBom = "2024.05.00"
androidxComposeCompiler = "1.5.13"
androidxCore = "1.13.1"
androidxHilt = "1.2.0"
androidxLifecycle = "2.8.0"
androidxNavigation = "2.7.7"
androidxRoom = "2.6.1"
androidxTestCore = "1.5.0"
androidxTestExt = "1.1.5"
androidxTestRunner = "1.5.2"
coroutines = "1.8.1"
hilt = "2.51"
junit = "4.13.2"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.20"

compiler = "3.1.4"
fragmentKtx = "1.7.1"

appcompat = "1.6.1"
mapsMobile = "4.6.1-full"
material = "1.12.0"
recyclerview = "1.3.2"
glide = "4.16.0"
retrofit = "2.9.0"
gson = "2.9.0"
retrofitLogs = "5.0.0-alpha.2"
kotlinGradlePlugin = "1.9.23"
espressoCore = "3.5.1"
jsoup = "1.17.2"




[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidxComposeCompiler" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4"}
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-test-core  = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
androidxCompat = { group = "androidx.appcompat", name = "appcompat",version.ref = "appcompat"}
googleMaterial = { group = "com.google.android.material", name = "material",version.ref = "material"}
maps-mobile = { module = "com.yandex.android:maps.mobile", version.ref = "mapsMobile" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview",version.ref = "recyclerview"}
glide = { group = "com.github.bumptech.glide", name = "glide",version.ref = "glide"}
glideAnnotations = { group = "com.github.bumptech.glide", name = "annotations",version.ref = "glide"}
glideCompiler = { group = "com.github.bumptech.glide", name = "compiler",version.ref = "glide"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit",version.ref = "retrofit"}
retrofitConverGson = { group = "com.squareup.retrofit2", name = "converter-gson",version.ref = "retrofit"}
retrofitConverScalars = { group = "com.squareup.retrofit2", name = "converter-scalars",version.ref = "retrofit"}
retrofitLogs = { group = "com.squareup.okhttp3", name = "logging-interceptor",version.ref = "retrofitLogs"}
googleGson = { group = "com.google.code.gson", name = "gson",version.ref = "gson"}
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compiler = { module = "com.android.databinding:compiler", version.ref = "compiler" }



[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
